### ISSUE TITLE
about vscode's vim.autoswitchinputmethod

### ISSUE THREAD

**Issue by ghost** [daipeihust/im-select#1]
it's my setting for vscode:
vim.autoswitchinputmethod.enable:true,
vim.autoswitchinputmethod.defaultIm:"1033",
vim.autoswitchinputmethod.obtainIMcmd:"E:\\VS_Code\\bin\\im-select.exe",
vim.autoswitchinputmethod.switchIMcmd:"E:\\VS_Code\\bin\\im-select.exe {im}"

and,i've already installed babun.but, i can't enjoy the im-select.who can help me ?

**Comment by 19778i5987** [comment]
* I found a issue:
I can use vim.autoswitchinputmethod normally,and i feel the problem is following:
The other day, due to power cut,my computer execute a restart, then ,just now, i found i can use im-select.In addition to this,I didn't do anything.

**Comment by daipeihust** [comment]
I want to know what's your output when you run "E:\VS_Code\bin\im-select.exe" in your babun.

**Comment by daipeihust** [comment]
you can change your config to:
```
vim.autoswitchinputmethod.obtainIMcmd:"E:\\VS_Code\\bin\\im-select.exe",
vim.autoswitchinputmethod.switchIMcmd:"E:\\VS_Code\\bin\\im-select.exe {im}"
```
And retry it.

**Comment by 19778i5987** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
This is my configuration.

**Comment by 19778i5987** [comment]
My babun output 2052, and the vscode configuration is the same as you described.

Sorry, I can't send the picture here.

**Comment by daipeihust** [comment]
Can you speak chinese?

**Comment by daipeihust** [comment]
May be your setting should be:

```
vim.autoswitchinputmethod.enable:true,
vim.autoswitchinputmethod.defaultIm:"1033",
vim.autoswitchinputmethod.obtainIMcmd:"E:\\VS_Code\\bin\\im-select.exe",
vim.autoswitchinputmethod.switchIMcmd:"E:\\VS_Code\\bin\\im-select.exe {im}"
```
