### ISSUE TITLE
Add another option for Linux configuration in README.md

### ISSUE THREAD

**Issue by VEL4EG** [daipeihust/im-select#10]
On some desktop environment (e.g cinnamon) ibus may not work properly. So another option is using [xkb-switch](https://github.com/ierton/xkb-switch) tool.

```
"vim.autoSwitchInputMethod.enable": true,
"vim.autoSwitchInputMethod.defaultIM": "us",
"vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/xkb-switch",
"vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/xkb-switch -s {im}"
```

I think mentioning it in README.md can save someone's time.

**Comment by daipeihust** [comment]
OK, I'll add it to readme, thank you
