### ISSUE TITLE
我使用的 win7 无论何种输入法，im-select 的结果一直是 2052

### ISSUE THREAD

**Issue by somenzz** [daipeihust/im-select#12]
Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ hello
bash: hello: command not found

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ /e/software/im-select.exe
2052

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ /e/software/im-select.exe 0

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ /e/software/im-select.exe 0

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ 你好
bash: 你好: command not found

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$ /e/software/im-select.exe
2052

Administrator@Win7-2019NTGGLF MINGW64 /e/software
$

**Comment by somenzz** [comment]
如果你用过 git bash，你应该可以看出来这就是在 git bash 中执行的。后来经过 1 个小时的测试终于发现问题所在： windows 版本的 im-select.exe 仅支持切换语言，而不支持切换语言内部的输入法。因此后来我在输入法设置里保留中文（中国，代码 2052）和英文（英国，代码 2057）两种语言，中文语言下仅保留搜狗五笔输入法，然后做如下配置，问题得到解决。
"vim.autoSwitchInputMethod.enable":true,
"vim.autoSwitchInputMethod.defaultIM":"2057",
"vim.autoSwitchInputMethod.obtainIMCmd":"D:\\Programs\\im-select.exe",
"vim.autoSwitchInputMethod.switchIMCmd":"D:\\Programs\\im-select.exe{im}",
"explorer.confirmDelete":false

**Comment by daipeihust** [comment]
厉害了
