### ISSUE TITLE
Mac OS升级到catalina后，提示无法运行，详见图

### ISSUE THREAD

**Issue by scottxing** [daipeihust/im-select#13]
![Screen Shot 2019-10-17 at 11 26 08](https://user-images.githubusercontent.com/12973305/66975433-12750200-f0d1-11e9-8cf5-aa2cf6dbda29.png)

**Comment by daipeihust** [comment]
好的 我修复一下

**Comment by daipeihust** [comment]
我发布了新版本 没有兼容性问题了

**Comment by scottxing** [comment]
谢谢。
