### ISSUE TITLE
brew package?

### ISSUE THREAD

**Issue by Willian-Zhang** [daipeihust/im-select#16]

**Comment by laishulu** [comment]
https://github.com/laishulu/macism/

mac上用这个工具，别的工具都有缺陷。
别的工具，切换输入法之后，必须要窗口失去焦点，再重获焦点，才能从激活中文输入法。
切换到英文输入法，大家都没什么问题。

**Comment by daipeihust** [comment]
coming soon

**Comment by aldanor** [comment]
@daipeihust Is it still in the plans?

**Comment by daipeihust** [comment]
@aldanor working on it.

**Comment by daipeihust** [comment]
@aldanor finished!!!

**Comment by mikaizhu** [comment]
> @aldanor finished!!!

when i try to use `brew install im-select`, it give me : Warning: No available formula with the name "im-select". Did you mean fselect?
brew can't find im-select

**Comment by daipeihust** [comment]
OK, will come soon

**Comment by daipeihust** [comment]
You can use `brew install im-select` now

**Comment by daipeihust** [comment]
> > You can use `brew install im-select` now
> 
> I got this message after running, is the name correct?
> 
> ```
> Warning: No available formula with the name "im-select". Did you mean fselect?
> ```

No, I found there is a problem too, I'm working on it, please wait a moment!
