### ISSUE TITLE
切换第三方中文输入法之后无法立即激活输入法

### ISSUE THREAD

**Issue by xinhangliu** [daipeihust/im-select#17]
您好！我在使用 im-select 的过程中遇到了一个问题。

```
OS: macOS Catalina 10.15.4
```

使用 im-select 切换第三方输入法（Squirrel、搜狗）之后，无法立即激活输入法，输入法选项只有一行 “..........”
<img width="279" alt="Screen Shot 2020-04-15 at 9 56 25 AM" src="https://user-images.githubusercontent.com/21138560/79290688-62f1de80-7eff-11ea-87cb-7031da5b3eb2.png">

只有当聚焦到另一个应用窗口之后，输入法才会被激活。

此现象并不能 100% 复现，偶尔能够成功切换。

**Comment by laishulu** [comment]
https://github.com/laishulu/macism/
mac上用这个工具，别的工具都有缺陷。

别的工具，切换输入法之后，
必须要窗口失去焦点，再重获焦点，才能从激活中文输入法。
切换到英文输入法，大家都没什么问题。

**Comment by xinhangliu** [comment]
@laishulu 非常好用，感谢。

**Comment by su27** [comment]
@laishulu 感谢，真是救我于水火
