### ISSUE TITLE
缺陷:只能切换输入法, 无法切换输入法的中英状态

### ISSUE THREAD

**Issue by Jackiexiao** [daipeihust/im-select#18]
不能切换输入法的中英状态还挺麻烦的，不过能够实现 `ctrl + P` 时切换到中文输入法吗?  我有一些笔记文件名是中文的.

**Comment by Jiang-Rain** [comment]
```json
"vim.insertModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["<Esc>", "<Shift>"]
    }
  ]
```
我用的搜狗，默认英文输入状态，不用安装这个脚本。原理是 j + j 后触发 esc 然后再触发 shift 恢复输入法初始状态，希望对你有帮助。

**Comment by daipeihust** [comment]
> 不能切换输入法的中英状态还挺麻烦的，不过能够实现 `ctrl + P` 时切换到中文输入法吗? 我有一些笔记文件名是中文的.

确实是做不到切换输入法的中英文状态，你可以自己探索一下替代方案

**Comment by daipeihust** [comment]
> ```json
> ```json
> "vim.insertModeKeyBindings": [
>   {
>     "before": ["j", "j"],
>     "after": ["<Esc>", "<Shift>"]
>   }
> ]
> ```
> 
> 
> 我用的搜狗，默认英文输入状态，不用安装这个脚本。原理是 j + j 后触发 esc 然后再触发 shift 恢复输入法初始状态，希望对你有帮助。
> ```

厉害了

**Comment by Jackiexiao** [comment]
我修改了这个vim的按键映射, 但不能切换中英文(shift键没有起到作用, 不知道为什么)

**Comment by daipeihust** [comment]
> 我修改了这个vim的按键映射, 但不能切换中英文(shift键没有起到作用, 不知道为什么)

这个你要自己研究一下原因了

**Comment by Jackiexiao** [comment]
@daipeihust 找到一个曲线救国的方法，可以让Esc回到normal模式后切换回中文(搜狗)输入法的英文状态


```json
  "vim.autoSwitchInputMethod.enable": true,
  "vim.autoSwitchInputMethod.defaultIM": "1033",
  "vim.autoSwitchInputMethod.obtainIMCmd": "C:\\im-select\\im-select.exe",
  "vim.autoSwitchInputMethod.switchIMCmd": "C:\\im-select\\im-select.exe {im} && C:\\im-select\\im-select.exe 2052",
```
增加一个`&& C:\\im-select\\im-select.exe 2052`，2052是搜狗输入法的值。

首先要设置搜狗输入法的默认状态为英文（其他输入法类似），然后按上面修改配置，回到normal后切换2次输入法（1次到美式英文，1次回到搜狗），在我电脑上切换比较顺畅。
![image](https://user-images.githubusercontent.com/18050469/91246350-350c8880-e782-11ea-9c28-f1b2044cb916.png)

**Comment by daipeihust** [comment]
可以 很棒

**Comment by Jackiexiao** [comment]
我擦秒回

**Comment by daipeihust** [comment]
hhh 有邮件通知

**Comment by Jackiexiao** [comment]
原来如此，我也设置一下

**Comment by NingerJohn** [comment]
不知道为啥，在vscode vim模式下，不行。
