### ISSUE TITLE
It stopped working with the last update of Windows 10

### ISSUE THREAD

**Issue by krasnovpro** [daipeihust/im-select#19]
subj. The application always returns zero (0).

**Comment by jdzgfan** [comment]
Yes, I also got the same problem.
I run it in cmd. It always returns 0. 
when run cmd as administrator, it still return 0.

I try to run it in powershell or git bash. It retuns 1033.
But I run "powershell ...\im-select.exe" in cmd. It still return 0. 
There is only 'cmd' option in vscode setting. It seems that it cannot be solved in this way.

**Comment by daipeihust** [comment]
I already mentioned it in README:
[https://github.com/daipeihust/im-select#windows-1](https://github.com/daipeihust/im-select#windows-1)

**Comment by jdzgfan** [comment]
Today I find it can be used in vscode-vim again with same settings.   Although it still returns 0 in cmd.
So it seems to be a problem of vscode-vim, not im-select in cmd.  Now it has been fixed.
Sorry to misjudge the source of the problem.

**Comment by krasnovpro** [comment]
> Today I find it can be used in vscode-vim again with same settings
How to fix it? I still have the problem.

**Comment by Jackiexiao** [comment]
![image](https://user-images.githubusercontent.com/18050469/95732611-8bdb0c80-0cb3-11eb-8859-19601a3d331d.png)

so how can I solve this problem ?

**Comment by krasnovpro** [comment]
My problem was that the "vim.autoSwitchInputMethod.enable" option was false =)
Now it works well from cmd (without git-bash).
