### ISSUE TITLE
Error switching to IM

### ISSUE THREAD

**Issue by Casper-Mars** [daipeihust/im-select#22]
使用报错
> Error switching to IM. err=Error: Command failed: /usr/local/bin/im-select com.apple.keylayout.US

环境：
mac10.15.6

**Comment by daipeihust** [comment]
英文输入法环境下 命令行执行这个命令试试：/usr/local/bin/im-select

**Comment by Casper-Mars** [comment]
改成使用
>  com.apple.keylayout.ABC

就行了
