### ISSUE TITLE
不能识别搜狗输入法通过 shift 切换的中英文状态

### ISSUE THREAD

**Issue by GanZhiXiong** [daipeihust/im-select#28]
因为我只使用 [搜狗输入法 for Mac - 支持全拼、双拼、模糊输入、苹果输入、云输入](https://pinyin.sogou.com/mac/) 这一个输入法，在需要使用英文时，我使用 shift 来切换（搜狗支持通过配置 shift 切换中英文）。
但是 macism 不能获取搜狗中英文状态，搜狗输入法在中文或英文状态下 macism 获取的输入源都只有一个，即 `com.sogou.inputmethod.sogou.pinyin`。

- 能解决这个问题吗？
   应该还有很多人有这样的需求。期待能解决。
- 或者有没有其他软件能识别搜狗输入法通过 shift 切换的中英文状态？

**Comment by daipeihust** [comment]
你可以把切换输入法的命令定义成按下shift按键 在另一个issue里有人给出解决方案了

**Comment by daipeihust** [comment]
https://github.com/daipeihust/im-select/issues/7#issuecomment-992178380
可以看看这个方法

**Comment by GanZhiXiong** [comment]
切换输入法换成 shift 的原理就是将 shift 按键映射为切换输入法的按键，它会带来如下问题：
1. 在 IDEA 中双击 shift 被配置成了快捷键，这样会导致双击 shift 无效。
2. 那将舍弃搜狗内置的英文输入了，也就不能再使用搜狗内置的英文状态 App 清单了。比如配置 vscode 在此清单，会导致切换到 vscode 后，按 shift 不能切换到中文。

问题 1 可以通过修改 idea 的快捷键，但是问题 2 对我来说是致命的。

**Comment by GanZhiXiong** [comment]
> [#7 (comment)](https://github.com/daipeihust/im-select/issues/7#issuecomment-992178380) 可以看看这个方法

我用的是 Mac

**Comment by daipeihust** [comment]
主要是搜狗输入法的状态 外界应该是很难获取 官方有开放的API和文档不？这个可以研究一下
BTW 第三方的输入法太多了 没法全部适配

**Comment by GanZhiXiong** [comment]
搜狗官方也没有开放 API 和文档。
 
我尝试了搜狗、百度、鼠须管，ShowyEdge和其他获取系统输入法的软件，都无法识别输入法通过 shift 切换的中英文状态。

**Comment by GanZhiXiong** [comment]
感觉应该是受 macOS API 限制了

**Comment by daipeihust** [comment]
是啊 macOS的APP有沙盒，没有开放的API 外界很难获取状态
