### ISSUE TITLE
切换输入法后，菜单栏的输入法变化了，但是按键按下的还是上次使用的输入法输出

### ISSUE THREAD

**Issue by GanZhiXiong** [daipeihust/im-select#29]
## 运行环境

```bash 
# ganzhixiong @ ganzhixiongdeMacBook-Pro-3 in ~ [14:28:17] C:1
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9028
```

### 1. 创建一个 Shell 脚本

```bash
#!/bin/zsh

# cd /usr/local/bin/
# echo $(pwd)
# open http://www.github.com/GanZhiXiong/1$(pwd)2/

current_input_source=$(/usr/local/bin/im-select)
echo $current_input_source

if [ "$current_input_source" = "com.apple.keylayout.ABC" ]; then
    /usr/local/bin/im-select com.sogou.inputmethod.sogou.pinyin
else
    /usr/local/bin/im-select com.apple.keylayout.ABC
fi
```

### 3. 复现

1. 打开 Chrome 随便定位一个输入框。
2. 切换输入法到 abc。
3. 切换应用到 VSCode。
4. 切换应用到 Chrome。
5. 切换输入法到搜狗。
   此时无法菜单栏输入法图标变成了搜狗，但是在输入框中打字，输出的确实英文。

**Comment by daipeihust** [comment]
在vscode中使用有这个问题吗

**Comment by GanZhiXiong** [comment]
也有这个问题。
不局限与这两个 App，其他 App 也是一样有这个问题。

**Comment by daipeihust** [comment]
你的意思是跨APP会发生这个问题？

**Comment by GanZhiXiong** [comment]
对的。我刚又测试了下，只有在如下情况都满足时才会发生：
- 从一个 App 切换到另一个 App。
- 光标必须定位到这个两个 App的输入框。
- 从英文切换到中文。

**Comment by GanZhiXiong** [comment]
不过你这个命令程序不适合我的应用场景了。
有如下原因：
- 中文下下输入字母后，不要按其他按键，再按 shift（我配置 shift 切换输入法），中文候选词界面不会消失。
- 英文下，按下 shift 后，快速按下字母 j，此时输出的英文，而没有显示中文候选词界面。

这两个问题比较严重，所以我不考虑使用命令了，直接调用系统切换输入法的快捷键（Ctrl + Spacebar）了。

**Comment by daipeihust** [comment]
你想要实现的功能 有专门软件做这个功能的
