### ISSUE TITLE
Switching IM does not affect immediately

### ISSUE THREAD

**Issue by odiak** [daipeihust/im-select#3]
I tried to do `im-select com.apple.inputmethod.Kotoeri.Roman` on terminal, but nothing was changed except IM icon on menu bar.
But after switching to other application, I could input with desired IM.

Is this a bug of macOS?

**Comment by daipeihust** [comment]
I don't know, maybe it's a bug of im-select.
Do you have problem using im-select in VSCodeVim?

**Comment by rhomel** [comment]
I have the same problem. The problem isn't related to VSCodeVim. I have the same issue when running from the terminal.

You have to switch windows (Cmd+Tab) before the change takes effect.

```
macOS High Sierra 10.13.6
```

**Comment by odiak** [comment]
@rhomel Same things were happened on my Mac (High Sierra).

However, I upgrade my Mac to Mojave few days ago, and those problems are gone.
im-select is correctly working on both terminal and VSCode. :tada:
