### ISSUE TITLE
mac 无法使用im-select

### ISSUE THREAD

**Issue by en-one** [daipeihust/im-select#36]
i can't run im-select， when i  input ```im-select``` in my terminal, it will show

<img width="407" alt="image" src="https://user-images.githubusercontent.com/36043386/184497145-045818fe-03a1-48a1-89e6-fec7c27176af.png">

**Comment by nshen** [comment]
是的，用homebrew安装的是interl版本，自己安装m1版本会报错。不知道怎么装m1版本

**Comment by G405G** [comment]
同求解决方案

**Comment by en-one** [comment]
我的目的是配置在vscode使用，可以切换大小写。我使用macism，这个工具，也可以达到相同目的，

**Comment by cloudylong** [comment]
apple 官方有解决办法：[Apple 无法检查 App 是否包含恶意软件](https://support.apple.com/zh-cn/guide/mac-help/mchleab3a043/mac?ivk_sa=1024320u)

**Comment by j5shi** [comment]
+1 (OS: MacOS 13.0, 处理器: M1 Max)
<img width="260" alt="image" src="https://user-images.githubusercontent.com/6829121/203551059-d251f0b6-3206-4231-8e4f-f8edb1d7f377.png">

**Comment by j5shi** [comment]
找到解决方案了, 在 Finder 中选中 im-select, 然后鼠标右键唤出菜单, 选中 “打开“, 然后在弹窗中继续选择 ”打开“. 之后就可以在命令行中使用 im-select 了.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/6829121/203551820-25c10946-9410-4e70-a4b6-e20da436b19d.png">
