### ISSUE TITLE
Input methods for KDE

### ISSUE THREAD

**Issue by ArtemT** [daipeihust/im-select#38]
I'm using Kubuntu 22.04, have reasons to avoid `ibus` or `fcitx`, just trying to keep everything by default :)

I have a problem with proposed `xkb-switch` method: it works, but it makes the language indicator disappear from system tray, so and global menu for VSCode.

It took a while to find the solution, here's my working `settings.json`:
```
{
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/bin/qdbus org.kde.keyboard /Layouts getLayout",
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/bin/qdbus org.kde.keyboard /Layouts setLayout {im}",
    "vim.autoSwitchInputMethod.defaultIM": "0",
    "vim.autoSwitchInputMethod.enable": true
}
```

Please, add it to `README.md`, cheers!

UPD: params added for `obtainIMCmd`.

**Comment by daipeihust** [comment]
you can commit your code and create a pull request, then I can merge it

**Comment by daipeihust** [comment]
I have added it to README
