### ISSUE TITLE
How to switch different modes of an input method?

### ISSUE THREAD

**Issue by iwfan** [daipeihust/im-select#4]
# How to switch different modes of an input method?

> I'm windows user.

I want to switch between different input ways, like from chinese to english.
other than from Chinese (Simplified) - US Keyboard(2052) to United States - English(1033).

Do you have any solutions?

**Comment by daipeihust** [comment]
Windows doesn't support an API to do this, So I have no idea to make it.

**Comment by iwfan** [comment]
Ok, maybe I've solved it.

I changed the config.

```json
  "vim.autoSwitchInputMethod.defaultIM": "2052",
  "vim.autoSwitchInputMethod.obtainIMCmd": "D:\\im-select.exe 1033 && D:\\im-select.exe 2052",
  "vim.autoSwitchInputMethod.switchIMCmd": "D:\\im-select.exe {im}",
```
It work for me!
