### ISSUE TITLE
Error executing lua callback: Vim:E475: Invalid value for argument cmd: 'im-select' is not executable

### ISSUE THREAD

**Issue by joket1999** [daipeihust/im-select#42]
MacOS: 10.15.7
NeoVim: 0.8.3

```lua
M.macInsertLeave = function()
  M.currentIM = vim.fn.system({ "im-select" })  --  Invalid value for argument cmd: 'im-select' is not executable
  vim.cmd(":silent :!im-select" .. " " .. M.defaultIM)
end
```

`
处理 InsertLeave 自动命令 "*" 时发生错误:
Error executing lua callback: Vim:E475: Invalid value for argument cmd: 'im-select' is not executable
stack traceback:
        [C]: in function 'system'
`

**Comment by daipeihust** [comment]
看起来是需要将im-select文件设置为可执行

**Comment by daipeihust** [comment]
你搜一下chmod命令的用法
