### ISSUE TITLE
用 im-select 自动切换输入法(鼠须管)，不生效， 必须手动切换才有效 

### ISSUE THREAD

**Issue by liaohui5** [daipeihust/im-select#45]
**Describe the bug**
在 MacOS 中，无法通过 [im-select](https://github.com/daipeihust/im-select) 命令来切换输入法
就算切换到了苹果自带的英文（状态栏都显示改变了），
再次输入， 用的还是鼠须管在输入

**To Reproduce**
1. 切换到 鼠须管
2. 用命令切换苹果自带的英文输入法(是启用的)
```sh
im-select com.apple.keylayout.ABC
```
3.（此时:状态栏已经改变）再次输入，发现并没有切换到英文输入法

**Expected behavior**
直接就切换输入法， 不要切换到英文输入法后，还是中文

**Screenshots**

https://user-images.githubusercontent.com/29266093/226532485-147b905d-a4dc-4b20-8aab-3fc1ef8ca8fa.mp4

**Flavor(please complete the following information):**
Select your flavor:
- [ ] ibus-rime
- [ ] fcitx-rime
- [ ] fcitx5-rime
- [x] Squirrel
- [ ] Trime
- [ ] Weasel

Package:
- OS: MacOs
- Version: 13.2.1 22D68 x86_64

**Additional context**

虽然用命令切换不生效， 但是手动用快捷键切换是会生效的

刚用这个，不太懂这是im-select的问题，还是输入法的问题

** end **

谢谢你做的这个项目，非常好用，哈哈 :) 👍 💯

**Comment by liaohui5** [comment]
> 

搜狗输入法好像是可以的, 但是用这个 鼠须管 就不行了

**Comment by daipeihust** [comment]
那可能是鼠须管在切换输入法的时候的bug 我测试过几款主流的输入法 比如搜狗、百度还有系统的输入法都是没有问题的

**Comment by liaohui5** [comment]
> 那可能是鼠须管在切换输入法的时候的bug 我测试过几款主流的输入法 比如搜狗、百度还有系统的输入法都是没有问题的

MacOS Ventura 百度输入法也有这个问题,只有搜狗没有

**Comment by daipeihust** [comment]
是这样吗 那我去研究一下

**Comment by liaohui5** [comment]
> 那你可能要用新版本的imselect，那个M1版本的

我是 19 款, 是 inter, 不是最新款的 M1 的

**Comment by daipeihust** [comment]
那很奇怪了

**Comment by daipeihust** [comment]
这个问题解决了？

**Comment by liaohui5** [comment]
老老实实用搜狗

**Comment by daipeihust** [comment]
😂

**Comment by rainzm** [comment]
same with #17 @liaohui5

**Comment by happyTonakai** [comment]
同样的问题，在鼠须管下无法切换到英文，在英文下可以切换到鼠须管

我发现readme中的例子不太对。。For example /usr/local/bin/im-select com.apple.keylayout.US

应该是 com.apple.keylayout.ABC，就可以正常切换了
