### ISSUE TITLE
window下使用，会导致c操作符的光标位置与样式不正确

### ISSUE THREAD

**Issue by kongku** [daipeihust/im-select#46]
win11，使用c操作符，例如ciw后，光标依然是normal模式下的光标，再输入字符后才变回正确的。如果ciw用在一行的最后一个单词，光标位置会在最后一个字符的前面，而不是行末，例如 let str=fun.value ,在value上使用ciw，光标会在点号.的前面，只是光标样式不正确，是normal时的样式，视觉样是在点号.的上面。但是，每个文档的第一次使用c操作符，光标位置与样式是正确的，从第二次往后就出现错误了。
![im-select](https://user-images.githubusercontent.com/29189288/226829720-177b9221-3eae-47df-8aa2-525669eb5e8e.gif)

**Comment by daipeihust** [comment]
这个问题是vscodevim的bug 跟我的插件没有太大关系
