### ISSUE TITLE
我想跟你联系一下

### ISSUE THREAD

**Issue by hadix-lin** [daipeihust/im-select#5]
您好,我写了一个IDEA的插件跟你这个命令行程序的功能差不多.
我希望您能为我提供一些帮助.

**Comment by daipeihust** [comment]
你需要什么帮助 这是我邮箱：daipeihust@gmail.com

**Comment by hadix-lin** [comment]
我的插件依赖本地方法的动态库,但是我自己又不会写,看了你的代码,我又不会编译打包.

另外有个问题,在我的插件调用的时候macOS会提示,TIS****的api需要在ui线程调用,你的代码并没有处理线程派发的问题.
所以想请您帮忙改一下你的代码,编译一下.

又或者,请您做为我的插件的贡献者,帮忙贡献这部分的代码和构建工具.我的库在
https://github.com/hadix-lin/ideavim_extension

**Comment by daipeihust** [comment]
我这个仓库只是mac和Windows平台上的命令行工具，用于切换输入法，然后在VSCodeVim的js代码中运行我的命令行工具，进行输入法的切换，你说的依赖动态库我也没有搞过哎
