### ISSUE TITLE
你好，仓库里没有已经编译好的.exe文件。

### ISSUE THREAD

**Issue by roro4ever** [daipeihust/im-select#52]
首页readme，windows 节的32bits/64bits二进制文件下载地址，都报错了，无法下载。
本想用源码自己编译，但这个机器上缺乏c的编译环境，又不敢折腾这个环境，毕竟是服务器....

希望作者把缺失的.exe文件补传一下，32/64bits都需要，非常感谢。

**Comment by roro4ever** [comment]
额，我看了下载的source code，里面有已经编译好的exe.......没想到啊，🙂。

**Comment by daipeihust** [comment]
🤣🤣🤣
