### ISSUE TITLE
可以只切换中英吗?

### ISSUE THREAD

**Issue by psuso** [daipeihust/im-select#7]
你好! 大兄弟, 可以只切换中英吗? 我不需要美式键盘啊!

识别不了一个输入法的中英两种状态

**Comment by daipeihust** [comment]
做不到，只能切换输入法

**Comment by zydxhs** [comment]
不能切换中英文状态，就很鸡肋了。

**Comment by daipeihust** [comment]
TSF

**Comment by zydxhs** [comment]
TSF 是输入法框架，貌似从 windows 8.1 以开始推出的。

**Comment by huangjj27** [comment]
TSF 和 IMM 我都不是很动，不过如果用 IMM 的话，`ImmSetConversionStatus` 和 `ImmGetConversionStatus` 是不是更好的函数呢？

**Comment by huangjj27** [comment]
> 我不需要美式键盘啊!
defaultIM 输入 1033试试？ 这个是美式键盘的编码

**Comment by transtone** [comment]
弄了个[新版](https://github.com/transtone/im-select)，在默认不加任何参数的情况下，发送一个 `Shift`，可以实现在不安装美式键盘的情况下，也能稳定切换到英文环境。

至于怎么还原到中文，我个人没这个需求，各位大佬可以继续改进。


https://github.com/transtone/im-select/blob/master/im-select-win/im-select/x64/Release/im-select.exe?raw=true

**Comment by daipeihust** [comment]
> 弄了个[新版](https://github.com/transtone/im-select)，在默认不加任何参数的情况下，发送一个 `Shift`，可以实现在不安装美式键盘的情况下，也能稳定切换到英文环境。
> 
> 至于怎么还原到中文，我个人没这个需求，各位大佬可以继续改进，[微软官方下载 vs2017](https://visualstudio.microsoft.com/zh-hans/vs/older-downloads/)，选择 `使用c++的桌面开发`，在`可选`里把 `windows 8.1 SDK 和 UCRT SDK` 选上，就可以调试编译了。
> 
> [transtone/im-select@`master`/im-select-win/im-select/x64/Release/im-select.exe?raw=true](https://github.com/transtone/im-select/blob/master/im-select-win/im-select/x64/Release/im-select.exe?raw=true&rgh-link-date=2021-12-13T07%3A22%3A46Z)

👍🏻

**Comment by scutxd** [comment]
> 做不到，只能切换输入法

![image](https://user-images.githubusercontent.com/28666253/148670509-81967539-6cd3-405e-8f15-934539b85358.png)
我发现Windows10中有这个选项，可以在搜狗输入法状态下，直接切换为无输入法状态，此时类似于英文键盘输入，并且切换回搜狗输入法时，搜狗输入法的中英文状态是保留的。
如果能把im-select切换为此种方式，是不是就可以在切换时依然保留搜狗输入法的中英文状态。

**Comment by daipeihust** [comment]
这个可以通过Ctrl+空格快捷键实现的话，可以直接模拟按键按下，不需要用到im-select，有些软件可以通过命令模拟快捷键，可以在配置里面把切换输入法的命令改成这种模拟按键按下的命令就行了

**Comment by yyancy** [comment]
@bushnerd  感谢兄弟!! 这绝对是很有用的选项, 之前都不知道!👍👍👍

**Comment by bushnerd** [comment]
> > 做不到，只能切换输入法
> 
> ![image](https://user-images.githubusercontent.com/28666253/148670509-81967539-6cd3-405e-8f15-934539b85358.png) 我发现Windows10中有这个选项，可以在搜狗输入法状态下，直接切换为无输入法状态，此时类似于英文键盘输入，并且切换回搜狗输入法时，搜狗输入法的中英文状态是保留的。 如果能把im-select切换为此种方式，是不是就可以在切换时依然保留搜狗输入法的中英文状态。

经过测试，这个方法并不能保留输入法的中英文选择，此方法无效，之前想当然了。

**Comment by bushnerd** [comment]
在Windows上我觉得可以用AutoHotKey来变通的解决这个问题。
int input_lang=0; //0为english, 1 为chinese
int vim_mode=0; //0为normal，1为insert
Esc::
vim_mode=0, input_lang=0

Shift::
    if vim_mode=1
        Send Shift//实现中英文输入法切换
    else 

记录下思路，但是没有输入法的接口实现这个很有点麻烦，而且如果在界面的其他窗口按下的Esc或者Shift会导致错误，哎，还是不行。

**Comment by yyancy** [comment]
@A-23187 看着很不错，明天我去试一下。
