### ISSUE TITLE
希望实现在 wsl 中切换 windows 的输入法

### ISSUE THREAD

**Issue by liaohui5** [daipeihust/im-select#81]
如题, 如果是 windows 想要 linux 的开发环境, 那么就需要使用 wsl, 但是在 wsl 中安装 im-select 无法切换 windows 的输入法状态

**Comment by keaising** [comment]
需要把 windows 版本的 im-select 放到一个 Windows 目录下，然后在 wsl 中访问，比如我的 im-select 放在 `D:/Programs/im-select.exe`，然后我的 Windows 的环境变量 Path 里添加了 `D:/Programs/` 目录，重启 wsl 应该就可以使用 im-select.exe 了

**Comment by liaohui5** [comment]
> 需要把 windows 版本的 im-select 放到一个 Windows 目录下，然后在 wsl 中访问，比如我的 im-select 放在 `D:/Programs/im-select.exe`，然后我的 Windows 的环境变量 Path 里添加了 `D:/Programs/` 目录，重启 wsl 应该就可以使用 im-select.exe 了

好的，已解决，非常感谢
