### ISSUE TITLE
macOS 15 之后很可能令 im-select 出现了未知的问题

### ISSUE THREAD

**Issue by nightire** [daipeihust/im-select#83]
请原谅我在标题上不得不含糊其辞，因为直到现在我仍无法断定问题的根源，希望有遇到类似情况的能提供更多的线索。

事由如下：

1. 我是因为 vscode 的 vim 插件而使用 im-select，因此这个问题也（暂时）限定于这个场景
2. 最近我同时升级了 macOS 15 和 vscode（每月例行升级），因此很难把这两个前因分开来分析。我最初认为是 vscode 升级产生的问题，但遍寻不着和我一样的用例，所以才逐渐把目光投向了 im-select，继而猜测可能是 macOS 的升级令 im-select 出现了未知问题

问题描述：
在 vscode 的 vim normal mode 下，长按或者快速连按 vim 的方向键（hjkl），会有很大概率在光标移动的过程中用按键覆盖光标经过的行或者字符。例如，按住 k 向上滚屏会忽然出现某一行文字被字符 k 替换掉了，非常恼人。

这个问题恶心之处就在于虽然有很大概率会出现，但又无法稳定复现条件。有时候连续几个小时不出问题，有时候在几分钟内连续出现好几次。最近几天我尝试了很多种办法来复现或者探查它的根源都无果，之所以会暂时认为是 im-select 出了问题是因为自昨晚开始我关闭了 vim 插件中用到 im-select 的功能，到目前为止还没有出现过问题。

希望有遇到类似情况的朋友补充更多的信息。

**Comment by SeanSelene** [comment]
应该是 vscodevim 插件的问题了，我这边使用的是 neovim，自己写的切换的逻辑没有问题。vscodevim 是一个模拟 vim 的插件，所以可能有各种问题，可以试试 neovim 插件，自己写配置

**Comment by nightire** [comment]
@road2coder 嗯，你应该说的没错。不过我直接换 neovim 了，vscode 下的 neovim 插件配置总是不能完美。
