### ISSUE TITLE
可以修改再次进入编辑模式时的输入法吗

### ISSUE THREAD

**Issue by liby** [daipeihust/im-select#9]
我特意在输入完中文后手动切换到中文输入法的英文模式再退出输入模式，但当我再次进入编辑模式时，输入法就自动变成了中文拼音模式，这样如果我需要输入代码的话，我还要手动切换到英文输入法，这样的话，还是很麻烦的
![vim](https://user-images.githubusercontent.com/38807139/55215254-21c75780-5234-11e9-8e5b-61ff3f1ed95f.gif)

**Comment by liby** [comment]
这是一个比较完整和常见的情况录屏
![case ](https://user-images.githubusercontent.com/38807139/55215857-1bd27600-5236-11e9-8d10-c3e1f6da5f72.gif)

**Comment by liby** [comment]
- 修改中文模式下的默认模式解决了这个问题
![Snipaste_2019-04-13_01-03-50](https://user-images.githubusercontent.com/38807139/56054020-410fca00-5d88-11e9-8414-40ad05ecf618.png)
- 顺便问一下除了babun, Win10下就没有其它终端支持im-select了吗,Babun太老旧了,很多报错信息,网上相关文档也很少.

**Comment by azhi09** [comment]
> * 修改中文模式下的默认模式解决了这个问题
>   ![Snipaste_2019-04-13_01-03-50](https://user-images.githubusercontent.com/38807139/56054020-410fca00-5d88-11e9-8414-40ad05ecf618.png)
> * 顺便问一下除了babun, Win10下就没有其它终端支持im-select了吗,Babun太老旧了,很多报错信息,网上相关文档也很少.

感谢老哥提供的思路
我用的是git bash

**Comment by daipeihust** [comment]
> * 修改中文模式下的默认模式解决了这个问题
>   ![Snipaste_2019-04-13_01-03-50](https://user-images.githubusercontent.com/38807139/56054020-410fca00-5d88-11e9-8414-40ad05ecf618.png)
> * 顺便问一下除了babun, Win10下就没有其它终端支持im-select了吗,Babun太老旧了,很多报错信息,网上相关文档也很少.

Windows自带的cmd和powershell上不行，其他第三方终端应该都是没问题的

**Comment by liby** [comment]
@daipeihust @azhi09 
那我本身就有git-bash,我去卸载了babun试试看,当初配置它花了好多心思,还一堆报错,谢谢

**Comment by liby** [comment]
@azhi09 
- 你在VSCode里修改这个vim的配置项也可以解决这个问题,就是从编辑模式切换到正常模式时不进行输入法切换
`"vim.autoSwitchInputMethod.switchIMCmd": "D:\\Run\\im-select.exe com.windows.keylayout.ABC {im}"`
